// This is an autogenerated file from Firebase Studio.
'use server';

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const GenerateDiagnosesInputSchema = z.object({
  profile: z.object({
    age: z.string(),
    sex: z.enum(['male', 'female', 'other']),
    chronic_conditions: z.array(z.string()),
    medications: z.array(z.string()),
    allergies: z.array(z.string()),
  }),
  symptoms: z.object({
    location: z.array(z.string()),
    type: z.array(z.string()),
    severity: z.number().min(1).max(10),
    duration: z.string(),
    onset: z.enum(['sudden', 'gradual']),
    radiation: z.string().optional(),
    triggers: z.array(z.string()),
    extras: z.array(z.string()),
  }),
  isPremium: z.boolean().default(false),
  language: z.string().default('en'),
});
export type GenerateDiagnosesInput = z.infer<typeof GenerateDiagnosesInputSchema>;

const DiagnosisSchema = z.object({
  condition: z.string(),
  explanation: z.string(),
  urgency: z.enum(['urgent', 'non-urgent', 'self-care']),
  next_steps: z.string(),
  confidence: z.number().min(0).max(100),
});

const GenerateDiagnosesOutputSchema = z.object({
  diagnoses: z.array(DiagnosisSchema),
});
export type GenerateDiagnosesOutput = z.infer<typeof GenerateDiagnosesOutputSchema>;

export async function generateDiagnoses(input: GenerateDiagnosesInput): Promise<GenerateDiagnosesOutput> {
  return generateDiagnosesFlow(input);
}

const generateDiagnosesPrompt = ai.definePrompt({
  name: 'generateDiagnosesPrompt',
  input: { schema: GenerateDiagnosesInputSchema },
  output: { schema: GenerateDiagnosesOutputSchema },
  prompt: `Act as a professional medical AI.
Lang: {{language}} (Translate results only).
Limit: {{#if isPremium}}5{{else}}3{{/if}} results.

Format (JSON):
{
  "diagnoses": [{
    "condition": "name",
    "explanation": "1-2 sentences",
    "urgency": "urgent"|"non-urgent"|"self-care",
    "next_steps": "actionable steps",
    "confidence": 1-100 (integer)
  }]
}

Inputs:
Patient: Age {{profile.age}}, {{profile.sex}}, Conditions: {{profile.chronic_conditions}}, Meds: {{profile.medications}}, Allergies: {{profile.allergies}}.
Symptoms: {{symptoms.location}}, {{symptoms.type}}, Severity: {{symptoms.severity}}/10, Duration: {{symptoms.duration}}, Onset: {{symptoms.onset}}.
{{#if symptoms.radiation}}Radiation: {{symptoms.radiation}}{{/if}}
Details: {{symptoms.triggers}}, {{symptoms.extras}}.`,
});

const aiResponseCache = new Map<string, GenerateDiagnosesOutput>();
const CACHE_TTL_MS = 5 * 60 * 1000;

const generateDiagnosesFlow = ai.defineFlow(
  {
    name: 'generateDiagnosesFlow',
    inputSchema: GenerateDiagnosesInputSchema,
    outputSchema: GenerateDiagnosesOutputSchema,
  },
  async (input) => {
    const lang = input.language.split('-')[0].toLowerCase();
    const cleanInput = { ...input, language: lang };

    const cacheKey = JSON.stringify(cleanInput);
    const cachedResponse = aiResponseCache.get(cacheKey);
    if (cachedResponse) return cachedResponse;

    const promptResponse = await generateDiagnosesPrompt(cleanInput);
    const validatedData = GenerateDiagnosesOutputSchema.parse(promptResponse.output);

    aiResponseCache.set(cacheKey, validatedData);
    setTimeout(() => aiResponseCache.delete(cacheKey), CACHE_TTL_MS);

    return validatedData;
  }
);
