// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A medical diagnostic AI agent.
 *
 * - generateDiagnoses - A function that handles the diagnosis generation process.
 * - GenerateDiagnosesInput - The input type for the generateDiagnoses function.
 * - GenerateDiagnosesOutput - The return type for the generateDiagnoses function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const GenerateDiagnosesInputSchema = z.object({
  profile: z.object({
    age: z.string().describe('The age of the patient (e.g., "30", "65+").'),
    sex: z.enum(['male', 'female', 'other']).describe('The sex of the patient.'),
    chronic_conditions: z.array(z.string()).describe("A list of the patient's chronic conditions."),
    medications: z.array(z.string()).describe("A list of the patient's medications."),
    allergies: z.array(z.string()).describe("A list of the patient's allergies."),
  }),
  symptoms: z.object({
    location: z.array(z.string()).describe('A list of locations of the symptoms.'),
    type: z.array(z.string()).describe('A list of the types of symptoms.'),
    severity: z.number().min(1).max(10).describe('The severity of the symptoms on a scale of 1 to 10.'),
    duration: z.string().describe('The duration of the symptoms.'),
    onset: z.enum(['sudden', 'gradual']).describe('The onset of the symptoms.'),
    radiation: z.string().optional().describe('The radiation of the symptoms, if any.'),
    triggers: z.array(z.string()).describe('A list of the triggers of the symptoms.'),
    extras: z
      .array(z.string())
      .describe(
        'A list of any extra information about the symptoms. This field is especially important if broad symptom types like "Digestive Issues" are selected, to provide specific manifestations.'
      ),
  }),
  // Language field removed
});
export type GenerateDiagnosesInput = z.infer<typeof GenerateDiagnosesInputSchema>;

const DiagnosisSchema = z.object({
  condition: z.string().describe('The name of the possible condition.'),
  explanation: z.string().describe('A brief explanation of the condition (1-2 sentences).'),
  urgency: z.enum(['urgent', 'non-urgent', 'self-care']).describe('The urgency level of the condition.'),
  next_steps: z
    .string()
    .describe(
      'Recommended next steps for the user (e.g., "Seek immediate medical attention", "Consult a doctor within 24 hours", "Rest and monitor symptoms").'
    ),
});

const GenerateDiagnosesOutputSchema = z.object({
  diagnoses: z
    .array(DiagnosisSchema)
    .length(5)
    .describe('An array of five possible diagnoses, each including condition, explanation, urgency, and next steps.'),
});
export type GenerateDiagnosesOutput = z.infer<typeof GenerateDiagnosesOutputSchema>;

export async function generateDiagnoses(input: GenerateDiagnosesInput): Promise<GenerateDiagnosesOutput> {
  return generateDiagnosesFlow(input);
}

const generateDiagnosesPrompt = ai.definePrompt({
  name: 'generateDiagnosesPrompt',
  input: { schema: GenerateDiagnosesInputSchema },
  output: { schema: GenerateDiagnosesOutputSchema },
  prompt: `You are a highly knowledgeable and professional medical diagnostic AI. Your purpose is to analyze patient data and symptoms to generate a concise, evidence-informed list of potential diagnoses, always maintaining a formal and objective tone. The reported symptom severity (on a scale of 1-10) and duration are critical factors; ensure your suggested diagnoses, their explanations, urgency, and next steps reflect the implications of these values. For instance, prolonged duration or high severity might elevate the concern for certain conditions or alter recommended actions. Carefully consider the provided symptom types, along with their locations and other details (especially in the 'extras' field if symptom types are broad), to differentiate between potential conditions and ensure your diagnoses are specific and relevant. Prioritize accuracy and clarity in your explanations. Your responses should be based on common medical knowledge and typical presentations of conditions.

Critically, ensure all diagnoses provided are medically appropriate and plausible for the patient's stated age (which might be a number or a string like "65+") and sex. For example, do not suggest conditions specific to one sex if the patient is of a different sex, or pediatric conditions for an adult patient, and vice-versa.

Your response MUST be a JSON object. This JSON object must contain a key named "diagnoses". The value of "diagnoses" MUST be an array containing exactly five distinct diagnosis objects.
Each diagnosis object in the "diagnoses" array must have the following structure and content:
- "condition": <string> The name of the possible condition.
- "explanation": <string, 1–2 sentences> A brief, clear explanation of the condition, avoiding overly technical jargon where simpler terms suffice for patient understanding.
- "urgency": one of ["urgent", "non-urgent", "self-care"]
- "next_steps": <string> Concise, actionable recommended next steps for the user, directly corresponding to the condition and its assigned urgency level.

The text content for "condition", "explanation", and "next_steps" fields should be in English. Do not translate the JSON keys or the "urgency" field's values.

Example output:
{
  "diagnoses": [
    {
      "condition": "Condition A",
      "explanation": "This is an explanation for condition A.",
      "urgency": "urgent",
      "next_steps": "Seek immediate medical attention at the nearest emergency room."
    },
    { "condition": "Condition B",
      "explanation": "This is an explanation for condition B.",
      "urgency": "non-urgent",
      "next_steps": "Schedule an appointment with your primary care physician within the next few days."
    },
    { "condition": "Condition C",
      "explanation": "This is an explanation for condition C.",
      "urgency": "self-care",
      "next_steps": "Rest, drink plenty of fluids, and monitor symptoms. If symptoms worsen or do not improve in 3 days, consult a doctor."
    }
  ]
}

Patient Profile:
Age: {{{profile.age}}}
Sex: {{{profile.sex}}}
Chronic Conditions: {{#each profile.chronic_conditions}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
Medications: {{#each profile.medications}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
Allergies: {{#each profile.allergies}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}

Symptoms:
Location: {{#each symptoms.location}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
Type: {{#each symptoms.type}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
Severity: {{{symptoms.severity}}}
Duration: {{{symptoms.duration}}}
Onset: {{{symptoms.onset}}}
{{#if symptoms.radiation}}Radiation: {{{symptoms.radiation}}}
{{/if}}Triggers: {{#each symptoms.triggers}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
Extras: {{#each symptoms.extras}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}`,
});

// Simple in-memory cache for AI responses
const aiResponseCache = new Map<string, GenerateDiagnosesOutput>();
const CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

const generateDiagnosesFlow = ai.defineFlow(
  {
    name: 'generateDiagnosesFlow',
    inputSchema: GenerateDiagnosesInputSchema,
    outputSchema: GenerateDiagnosesOutputSchema,
  },
  async (input) => {
    const cacheKey = JSON.stringify(input); // Create a cache key from the input
    const cachedResponse = aiResponseCache.get(cacheKey);

    if (cachedResponse) {
      console.log('Serving AI response from cache.');
      return cachedResponse;
    }

    const promptResponse = await generateDiagnosesPrompt(input);

    // Explicitly validate the output from the prompt against the schema
    const validationResult = GenerateDiagnosesOutputSchema.safeParse(promptResponse.output);

    if (!validationResult.success) {
      // Log the validation error details on the server for debugging
      console.error('Output schema validation failed in generateDiagnosesFlow:', validationResult.error.format());
      console.error('Data that failed validation:', promptResponse.output);
      // Throw an error that will be caught by the client's onError handler
      throw new Error(`AI output did not match the expected structure: ${validationResult.error.message}`);
    }

    const validatedData = validationResult.data;

    // Store the successful response in cache with a TTL
    aiResponseCache.set(cacheKey, validatedData);
    setTimeout(() => aiResponseCache.delete(cacheKey), CACHE_TTL_MS);

    // If validation is successful, validationResult.data is the correctly typed output
    return validatedData;
  }
);
