// This is an autogenerated file from Firebase Studio.
'use server';

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const GenerateDiagnosesInputSchema = z.object({
  profile: z.object({
    age: z.string(),
    sex: z.enum(['male', 'female', 'other']),
    chronic_conditions: z.array(z.string()),
    medications: z.array(z.string()),
    allergies: z.array(z.string()),
  }),
  symptoms: z.object({
    location: z.array(z.string()),
    type: z.array(z.string()),
    severity: z.number().min(1).max(10),
    duration: z.string(),
    onset: z.enum(['sudden', 'gradual']),
    radiation: z.string().optional(),
    triggers: z.array(z.string()),
    extras: z.array(z.string()),
    symptomImageUrl: z.string().optional(),
  }),
  isPremium: z.boolean().default(false),
  language: z.string().default('en'),
});
export type GenerateDiagnosesInput = z.infer<typeof GenerateDiagnosesInputSchema>;

const DiagnosisSchema = z.object({
  condition: z.string(),
  explanation: z.string(),
  urgency: z.enum(['urgent', 'non-urgent', 'self-care']),
  next_steps: z.string(),
  confidence: z.number().min(0).max(100),
});

const GenerateDiagnosesOutputSchema = z.object({
  diagnoses: z.array(DiagnosisSchema),
});
export type GenerateDiagnosesOutput = z.infer<typeof GenerateDiagnosesOutputSchema>;

export async function generateDiagnoses(input: GenerateDiagnosesInput): Promise<GenerateDiagnosesOutput> {
  return generateDiagnosesFlow(input);
}

const aiResponseCache = new Map<string, GenerateDiagnosesOutput>();
const CACHE_TTL_MS = 5 * 60 * 1000;

const generateDiagnosesFlow = ai.defineFlow(
  {
    name: 'generateDiagnosesFlow',
    inputSchema: GenerateDiagnosesInputSchema,
    outputSchema: GenerateDiagnosesOutputSchema,
  },
  async (input) => {
    const lang = input.language.split('-')[0].toLowerCase();
    const cleanInput = { ...input, language: lang };

    const cacheKey = JSON.stringify(cleanInput);
    const cachedResponse = aiResponseCache.get(cacheKey);
    if (cachedResponse) return cachedResponse;

    // Construct the text prompt
    let promptText = `Act as a professional medical AI.
Lang: ${cleanInput.language} (Translate results only).
Limit: ${cleanInput.isPremium ? 5 : 3} results.

Format (JSON):
{
  "diagnoses": [{
    "condition": "name",
    "explanation": "1-2 sentences",
    "urgency": "urgent"|"non-urgent"|"self-care",
    "next_steps": "actionable steps",
    "confidence": 1-100 (integer)
  }]
}

Inputs:
Patient: Age ${cleanInput.profile.age}, ${cleanInput.profile.sex}, Conditions: ${cleanInput.profile.chronic_conditions.join(', ')}, Meds: ${cleanInput.profile.medications.join(', ')}, Allergies: ${cleanInput.profile.allergies.join(', ')}.
Symptoms: ${cleanInput.symptoms.location.join(', ')}, ${cleanInput.symptoms.type.join(', ')}, Severity: ${cleanInput.symptoms.severity}/10, Duration: ${cleanInput.symptoms.duration}, Onset: ${cleanInput.symptoms.onset}.
`;

    if (cleanInput.symptoms.radiation) {
      promptText += `Radiation: ${cleanInput.symptoms.radiation}\n`;
    }

    promptText += `Details: ${cleanInput.symptoms.triggers.join(', ')}, ${cleanInput.symptoms.extras.join(', ')}.`;

    // Prepare content for multimodal input
    const promptContent: any[] = [{ text: promptText }];

    // Add image if available
    if (cleanInput.symptoms.symptomImageUrl) {
      promptContent.push({ media: { url: cleanInput.symptoms.symptomImageUrl } });
      promptText += '\n(An image of the symptom is attached for analysis.)';
    }

    const response = await ai.generate({
      model: 'googleai/gemini-2.5-flash-lite',
      prompt: promptContent,
      output: { schema: GenerateDiagnosesOutputSchema },
    });

    if (!response.output) {
      throw new Error('Failed to generate diagnosis');
    }

    const validatedData = response.output;

    aiResponseCache.set(cacheKey, validatedData);
    setTimeout(() => aiResponseCache.delete(cacheKey), CACHE_TTL_MS);

    return validatedData;
  }
);
