// Comprehensive localized medical data
export const medicalData: Record<string, { conditions: string[]; meds: string[]; allergies: string[] }> = {
  en: {
    conditions: [
      'Diabetes',
      'Hypertension',
      'Asthma',
      'Heart Disease',
      'CKD',
      'Arthritis',
      'Migraine',
      'Anxiety',
      'Depression',
      'Obesity',
      'Epilepsy',
      'COPD',
      'Lupus',
      'Anemia',
    ],
    meds: [
      'Metformin',
      'Lisinopril',
      'Atorvastatin',
      'Amlodipine',
      'Omeprazole',
      'Albuterol',
      'Gabapentin',
      'Sertraline',
      'Aspirin',
      'Ibuprofen',
      'Acetaminophen',
      'Amoxicillin',
      'Insulin',
    ],
    allergies: [
      'Penicillin',
      'Peanuts',
      'Shellfish',
      'Latex',
      'Dust Mites',
      'Pollen',
      'Bee Stings',
      'Dairy',
      'Eggs',
      'Soy',
      'Wheat',
      'Iodine',
    ],
  },
  id: {
    conditions: [
      'Diabetes',
      'Hipertensi',
      'Asma',
      'Penyakit Jantung',
      'Gagal Ginjal',
      'Artritis',
      'Migrain',
      'Kecemasan',
      'Depresi',
      'Obesitas',
      'Epilepsi',
      'PPOK',
      'Lupus',
      'Anemia',
    ],
    meds: [
      'Metformin',
      'Lisinopril',
      'Atorvastatin',
      'Amlodipine',
      'Omeprazole',
      'Salbutamol',
      'Gabapentin',
      'Sertraline',
      'Aspirin',
      'Ibuprofen',
      'Parasetamol',
      'Amoksisilin',
      'Insulin',
    ],
    allergies: [
      'Penisilin',
      'Kacang-kacangan',
      'Seafood',
      'Lateks',
      'Debu',
      'Serbuk Sari',
      'Sengatan Lebah',
      'Produk Susu',
      'Telur',
      'Kedelai',
      'Gandum',
      'Iodium',
    ],
  },
  es: {
    conditions: [
      'Diabetes',
      'Hipertensión',
      'Asma',
      'Cardiopatía',
      'ERC',
      'Artritis',
      'Migraña',
      'Ansiedad',
      'Depresión',
      'Obesidad',
      'Epilepsia',
      'EPOC',
      'Lupus',
      'Anemia',
    ],
    meds: [
      'Metformina',
      'Lisinopril',
      'Atorvastatina',
      'Amlodipino',
      'Omeprazol',
      'Albuterol',
      'Gabapentina',
      'Sertralina',
      'Aspirina',
      'Ibuprofeno',
      'Acetaminofén',
      'Amoxicilina',
      'Insulina',
    ],
    allergies: [
      'Penicilina',
      'Maní',
      'Mariscos',
      'Látex',
      'Ácaros',
      'Polen',
      'Picadura de abeja',
      'Lácteos',
      'Huevos',
      'Soya',
      'Trigo',
      'Yodo',
    ],
  },
  fr: {
    conditions: [
      'Diabète',
      'Hypertension',
      'Asthme',
      'Maladie Cardiaque',
      'Insuffisance Rénale',
      'Arthrite',
      'Migraine',
      'Anxiété',
      'Dépression',
      'Obésité',
      'Épilepsie',
      'BPCO',
      'Lupus',
      'Anémie',
    ],
    meds: [
      'Metformine',
      'Lisinopril',
      'Atorvastatine',
      'Amlodipine',
      'Oméprazole',
      'Albutérol',
      'Gabapentine',
      'Sertraline',
      'Aspirine',
      'Ibuprofène',
      'Paracétamol',
      'Amoxicilline',
      'Insuline',
    ],
    allergies: [
      'Pénicilline',
      'Arachides',
      'Fruits de mer',
      'Latex',
      'Acariens',
      'Pollen',
      "Piqûre d'abeille",
      'Produits laitiers',
      'Oeufs',
      'Soja',
      'Blé',
      'Iode',
    ],
  },
};

export const ageIconMap: { [key: string]: string } = {
  infant: '/images/age_icons/infant.webp',
  toddler: '/images/age_icons/toddler.webp',
  preschooler: '/images/age_icons/preschooler.webp',
  schoolage: '/images/age_icons/schoolage.webp',
  adolescent: '/images/age_icons/adolescent.webp',
  youngadult: '/images/age_icons/youngadult.webp',
  middleageadult: '/images/age_icons/middleageadult.webp',
  olderadult: '/images/age_icons/olderadult.webp',
};

export const getAgeIconAndLabel = (ageInput: number | undefined, t: any): { iconPath: string; label: string } => {
  const numericAge = ageInput ?? 0;
  let iconKey: keyof typeof ageIconMap;
  if (numericAge === 0) iconKey = 'infant';
  else if (numericAge >= 1 && numericAge <= 3) iconKey = 'toddler';
  else if (numericAge >= 4 && numericAge <= 5) iconKey = 'preschooler';
  else if (numericAge >= 6 && numericAge <= 12) iconKey = 'schoolage';
  else if (numericAge >= 13 && numericAge <= 18) iconKey = 'adolescent';
  else if (numericAge >= 19 && numericAge <= 40) iconKey = 'youngadult';
  else if (numericAge >= 41 && numericAge <= 64) iconKey = 'middleageadult';
  else if (numericAge >= 65) iconKey = 'olderadult';
  else iconKey = 'youngadult';

  let labelText = `${numericAge}`;
  if (numericAge >= 65) labelText = '65+';
  return { iconPath: ageIconMap[iconKey], label: `${t('age')}: ${labelText}` };
};
