export const symptomTypesByLanguage: Record<string, { value: string; label: string }[]> = {
  en: [
    { value: 'abdominal-pain-discomfort', label: 'Abdominal Pain / Discomfort' },
    { value: 'anxiety-new-worsening', label: 'Anxiety (New or Worsening)' },
    { value: 'bleeding', label: 'Bleeding' },
    { value: 'bruising-unexplained', label: 'Bruising (Unexplained or Excessive)' },
    { value: 'chills', label: 'Chills' },
    { value: 'confusion-disorientation', label: 'Confusion or Disorientation' },
    { value: 'constipation', label: 'Constipation' },
    { value: 'cough', label: 'Cough (Persistent or Severe)' },
    { value: 'depression-new-worsening', label: 'Depression (New or Worsening)' },
    { value: 'diarrhea', label: 'Diarrhea' },
    { value: 'discharge-abnormal', label: 'Discharge (Abnormal)' },
    { value: 'dizziness', label: 'Dizziness' },
    { value: 'ear-pain-or-discharge', label: 'Ear Pain or Discharge' },
    { value: 'eye-pain-or-redness', label: 'Eye Pain or Redness' },
    { value: 'fainting-syncope', label: 'Fainting / Syncope' },
    { value: 'fatigue-extreme', label: 'Fatigue (Extreme or Prolonged)' },
    { value: 'fever', label: 'Fever' },
    { value: 'headache', label: 'Headache' },
    { value: 'hearing-loss-new', label: 'Hearing Loss (New or Sudden)' },
    { value: 'irritability-agitation-unusual', label: 'Irritability or Agitation (Unusual)' },
    { value: 'itching-persistent', label: 'Itching (Persistent or Severe)' },
    { value: 'jaw-pain', label: 'Jaw Pain' },
    { value: 'joint-pain', label: 'Joint Pain' },
    { value: 'lightheadedness', label: 'Lightheadedness' },
    { value: 'lump-mass-new', label: 'Lump or Mass (New)' },
    { value: 'malaise-general-unwellness', label: 'Malaise / General Feeling of Unwellness' },
    { value: 'memory-problems-new', label: 'Memory Problems (New or Worsening)' },
    { value: 'muscle-cramps', label: 'Muscle Cramps' },
    { value: 'nasal-congestion', label: 'Nasal Congestion' },
    { value: 'nausea', label: 'Nausea' },
    { value: 'numbness', label: 'Numbness' },
    { value: 'other-symptom', label: 'Other Symptom (Describe in Extras)' },
    { value: 'pain-ache', label: 'Pain / Ache' },
    { value: 'rash', label: 'Rash' },
    { value: 'runny-nose', label: 'Runny Nose' },
    { value: 'shortness-of-breath', label: 'Shortness of Breath / Difficulty Breathing' },
    { value: 'skin-discoloration-new', label: 'Skin Discoloration (New)' },
    { value: 'skin-lesion-new', label: 'Skin Lesion (New or Changing)' },
    { value: 'sore-throat', label: 'Sore Throat' },
    { value: 'stiff-neck', label: 'Stiff Neck' },
    { value: 'sweats-excessive', label: 'Sweats (Excessive or Night Sweats)' },
    { value: 'swelling-edema', label: 'Swelling / Edema' },
    { value: 'tingling-pins-needles', label: 'Tingling / Pins and Needles' },
    { value: 'tinnitus-ringing-ears', label: 'Tinnitus (Ringing in Ears)' },
    { value: 'urinary-issues', label: 'Urinary Issues (e.g., Pain, Frequency, Blood, Odor)' },
    { value: 'vision-blurred-double', label: 'Vision - Blurred or Double' },
    { value: 'vision-loss-partial-complete', label: 'Vision - Partial or Complete Loss' },
    { value: 'vomiting', label: 'Vomiting' },
    { value: 'weakness-muscle', label: 'Weakness (Muscle)' },
    { value: 'bloating', label: 'Bloating' },
    { value: 'heartburn', label: 'Heartburn' },
    { value: 'back-pain', label: 'Back Pain' },
  ],

  id: [
    { value: 'abdominal-pain-discomfort', label: 'Nyeri / Ketidaknyamanan Perut' },
    { value: 'anxiety-new-worsening', label: 'Kecemasan (Baru atau Memburuk)' },
    { value: 'bleeding', label: 'Perdarahan' },
    { value: 'bruising-unexplained', label: 'Memar (Tanpa Sebab Jelas atau Berlebihan)' },
    { value: 'chills', label: 'Menggigil' },
    { value: 'confusion-disorientation', label: 'Kebingungan atau Disorientasi' },
    { value: 'constipation', label: 'Sembelit' },
    { value: 'cough', label: 'Batuk (Persisten atau Berat)' },
    { value: 'depression-new-worsening', label: 'Depresi (Baru atau Memburuk)' },
    { value: 'diarrhea', label: 'Diare' },
    { value: 'discharge-abnormal', label: 'Keluarnya Cairan Abnormal' },
    { value: 'dizziness', label: 'Pusing' },
    { value: 'ear-pain-or-discharge', label: 'Nyeri Telinga atau Cairan' },
    { value: 'eye-pain-or-redness', label: 'Nyeri atau Kemerahan Mata' },
    { value: 'fainting-syncope', label: 'Pingsan' },
    { value: 'fatigue-extreme', label: 'Kelelahan (Berat atau Berkepanjangan)' },
    { value: 'fever', label: 'Demam' },
    { value: 'headache', label: 'Sakit Kepala' },
    { value: 'hearing-loss-new', label: 'Gangguan Pendengaran (Baru atau Mendadak)' },
    { value: 'irritability-agitation-unusual', label: 'Mudah Marah atau Gelisah (Tidak Biasa)' },
    { value: 'itching-persistent', label: 'Gatal (Persisten atau Berat)' },
    { value: 'jaw-pain', label: 'Nyeri Rahang' },
    { value: 'joint-pain', label: 'Nyeri Sendi' },
    { value: 'lightheadedness', label: 'Rasa Melayang' },
    { value: 'lump-mass-new', label: 'Benjolan atau Massa (Baru)' },
    { value: 'malaise-general-unwellness', label: 'Tidak Enak Badan' },
    { value: 'memory-problems-new', label: 'Masalah Ingatan (Baru atau Memburuk)' },
    { value: 'muscle-cramps', label: 'Kram Otot' },
    { value: 'nasal-congestion', label: 'Hidung Tersumbat' },
    { value: 'nausea', label: 'Mual' },
    { value: 'numbness', label: 'Mati Rasa' },
    { value: 'other-symptom', label: 'Gejala Lain (Jelaskan di Tambahan)' },
    { value: 'pain-ache', label: 'Nyeri' },
    { value: 'rash', label: 'Ruam' },
    { value: 'runny-nose', label: 'Pilek' },
    { value: 'shortness-of-breath', label: 'Sesak Napas' },
    { value: 'skin-discoloration-new', label: 'Perubahan Warna Kulit (Baru)' },
    { value: 'skin-lesion-new', label: 'Lesi Kulit (Baru atau Berubah)' },
    { value: 'sore-throat', label: 'Sakit Tenggorokan' },
    { value: 'stiff-neck', label: 'Leher Kaku' },
    { value: 'sweats-excessive', label: 'Keringat Berlebih / Keringat Malam' },
    { value: 'swelling-edema', label: 'Pembengkakan / Edema' },
    { value: 'tingling-pins-needles', label: 'Kesemutan' },
    { value: 'tinnitus-ringing-ears', label: 'Telinga Berdenging' },
    { value: 'urinary-issues', label: 'Masalah Saluran Kemih' },
    { value: 'vision-blurred-double', label: 'Penglihatan Kabur atau Ganda' },
    { value: 'vision-loss-partial-complete', label: 'Kehilangan Penglihatan Sebagian atau Total' },
    { value: 'vomiting', label: 'Muntah' },
    { value: 'weakness-muscle', label: 'Kelemahan Otot' },
    { value: 'bloating', label: 'Perut Kembung' },
    { value: 'heartburn', label: 'Nyeri Ulu Hati' },
    { value: 'back-pain', label: 'Nyeri Punggung' },
  ],

  es: [
    { value: 'abdominal-pain-discomfort', label: 'Dolor / Molestia Abdominal' },
    { value: 'anxiety-new-worsening', label: 'Ansiedad (Nueva o Empeorada)' },
    { value: 'bleeding', label: 'Sangrado' },
    { value: 'bruising-unexplained', label: 'Moretones (Inexplicables o Excesivos)' },
    { value: 'chills', label: 'Escalofríos' },
    { value: 'confusion-disorientation', label: 'Confusión o Desorientación' },
    { value: 'constipation', label: 'Estreñimiento' },
    { value: 'cough', label: 'Tos (Persistente o Grave)' },
    { value: 'depression-new-worsening', label: 'Depresión (Nueva o Empeorada)' },
    { value: 'diarrhea', label: 'Diarrea' },
    { value: 'discharge-abnormal', label: 'Secreción Anormal' },
    { value: 'dizziness', label: 'Mareo' },
    { value: 'ear-pain-or-discharge', label: 'Dolor o Secreción del Oído' },
    { value: 'eye-pain-or-redness', label: 'Dolor o Enrojecimiento Ocular' },
    { value: 'fainting-syncope', label: 'Desmayo' },
    { value: 'fatigue-extreme', label: 'Fatiga Extrema o Prolongada' },
    { value: 'fever', label: 'Fiebre' },
    { value: 'headache', label: 'Dolor de Cabeza' },
    { value: 'hearing-loss-new', label: 'Pérdida Auditiva Repentina' },
    { value: 'irritability-agitation-unusual', label: 'Irritabilidad o Agitación Inusual' },
    { value: 'itching-persistent', label: 'Picazón Persistente o Grave' },
    { value: 'jaw-pain', label: 'Dolor de Mandíbula' },
    { value: 'joint-pain', label: 'Dolor Articular' },
    { value: 'lightheadedness', label: 'Sensación de Desvanecimiento' },
    { value: 'lump-mass-new', label: 'Bulto o Masa Nueva' },
    { value: 'malaise-general-unwellness', label: 'Malestar General' },
    { value: 'memory-problems-new', label: 'Problemas de Memoria Nuevos' },
    { value: 'muscle-cramps', label: 'Calambres Musculares' },
    { value: 'nasal-congestion', label: 'Congestión Nasal' },
    { value: 'nausea', label: 'Náuseas' },
    { value: 'numbness', label: 'Entumecimiento' },
    { value: 'other-symptom', label: 'Otro Síntoma (Describir en Extras)' },
    { value: 'pain-ache', label: 'Dolor' },
    { value: 'rash', label: 'Erupción Cutánea' },
    { value: 'runny-nose', label: 'Secreción Nasal' },
    { value: 'shortness-of-breath', label: 'Dificultad para Respirar' },
    { value: 'skin-discoloration-new', label: 'Cambio de Color en la Piel' },
    { value: 'skin-lesion-new', label: 'Lesión Cutánea Nueva o Cambiante' },
    { value: 'sore-throat', label: 'Dolor de Garganta' },
    { value: 'stiff-neck', label: 'Rigidez en el Cuello' },
    { value: 'sweats-excessive', label: 'Sudoración Excesiva o Nocturna' },
    { value: 'swelling-edema', label: 'Hinchazón / Edema' },
    { value: 'tingling-pins-needles', label: 'Hormigueo' },
    { value: 'tinnitus-ringing-ears', label: 'Zumbido en los Oídos' },
    { value: 'urinary-issues', label: 'Problemas Urinarios' },
    { value: 'vision-blurred-double', label: 'Visión Borrosa o Doble' },
    { value: 'vision-loss-partial-complete', label: 'Pérdida Parcial o Total de la Visión' },
    { value: 'vomiting', label: 'Vómitos' },
    { value: 'weakness-muscle', label: 'Debilidad Muscular' },
    { value: 'bloating', label: 'Hinchazón Abdominal' },
    { value: 'heartburn', label: 'Acidez Estomacal' },
    { value: 'back-pain', label: 'Dolor de Espalda' },
  ],

  fr: [
    { value: 'abdominal-pain-discomfort', label: 'Douleur / Inconfort Abdominal' },
    { value: 'anxiety-new-worsening', label: 'Anxiété (Nouvelle ou Aggravée)' },
    { value: 'bleeding', label: 'Saignement' },
    { value: 'bruising-unexplained', label: 'Ecchymoses Inexpliquées ou Excessives' },
    { value: 'chills', label: 'Frissons' },
    { value: 'confusion-disorientation', label: 'Confusion ou Désorientation' },
    { value: 'constipation', label: 'Constipation' },
    { value: 'cough', label: 'Toux Persistante ou Sévère' },
    { value: 'depression-new-worsening', label: 'Dépression (Nouvelle ou Aggravée)' },
    { value: 'diarrhea', label: 'Diarrhée' },
    { value: 'discharge-abnormal', label: 'Écoulement Anormal' },
    { value: 'dizziness', label: 'Étourdissement' },
    { value: 'ear-pain-or-discharge', label: 'Douleur ou Écoulement de l’Oreille' },
    { value: 'eye-pain-or-redness', label: 'Douleur ou Rougeur Oculaire' },
    { value: 'fainting-syncope', label: 'Évanouissement' },
    { value: 'fatigue-extreme', label: 'Fatigue Extrême ou Prolongée' },
    { value: 'fever', label: 'Fièvre' },
    { value: 'headache', label: 'Maux de Tête' },
    { value: 'hearing-loss-new', label: 'Perte Auditive Soudaine' },
    { value: 'irritability-agitation-unusual', label: 'Irritabilité ou Agitation Inhabituelle' },
    { value: 'itching-persistent', label: 'Démangeaisons Persistantes ou Sévères' },
    { value: 'jaw-pain', label: 'Douleur à la Mâchoire' },
    { value: 'joint-pain', label: 'Douleur Articulaire' },
    { value: 'lightheadedness', label: 'Sensation de Tête Légère' },
    { value: 'lump-mass-new', label: 'Masse ou Grosseur Nouvelle' },
    { value: 'malaise-general-unwellness', label: 'Malaise Général' },
    { value: 'memory-problems-new', label: 'Troubles de la Mémoire Nouveaux' },
    { value: 'muscle-cramps', label: 'Crampes Musculaires' },
    { value: 'nasal-congestion', label: 'Congestión Nasale' },
    { value: 'nausea', label: 'Nausées' },
    { value: 'numbness', label: 'Engourdissement' },
    { value: 'other-symptom', label: 'Autre Symptôme (Décrire)' },
    { value: 'pain-ache', label: 'Douleur' },
    { value: 'rash', label: 'Éruption Cutanée' },
    { value: 'runny-nose', label: 'Nez Qui Coule' },
    { value: 'shortness-of-breath', label: 'Essoufflement' },
    { value: 'skin-discoloration-new', label: 'Décoloration de la Peau' },
    { value: 'skin-lesion-new', label: 'Lésion Cutanée Nouvelle ou Changeante' },
    { value: 'sore-throat', label: 'Mal de Gorge' },
    { value: 'stiff-neck', label: 'Raideur de la Nuque' },
    { value: 'sweats-excessive', label: 'Transpiration Excessive ou Nocturne' },
    { value: 'swelling-edema', label: 'Gonflement / Œdème' },
    { value: 'tingling-pins-needles', label: 'Picotements' },
    { value: 'tinnitus-ringing-ears', label: 'Bourdonnements d’Oreilles' },
    { value: 'urinary-issues', label: 'Problèmes Urinaires' },
    { value: 'vision-blurred-double', label: 'Vision Floue ou Double' },
    { value: 'vision-loss-partial-complete', label: 'Perte Partielle ou Totale de la Vision' },
    { value: 'vomiting', label: 'Vomissements' },
    { value: 'weakness-muscle', label: 'Faiblesse Musculaire' },
    { value: 'bloating', label: 'Ballonnements' },
    { value: 'heartburn', label: 'Brûlures d’Estomac' },
    { value: 'back-pain', label: 'Douleur Dorsale' },
  ],
};

// Sort them by label for each language
Object.keys(symptomTypesByLanguage).forEach((lang) => {
  symptomTypesByLanguage[lang].sort((a, b) => a.label.localeCompare(b.label));
});

export const regionIds3D = [
  'head',
  'neck',
  'chest',
  'abdomen',
  'pelvis',
  'left-shoulder',
  'right-shoulder',
  'left-arm',
  'right-arm',
  'left-hand',
  'right-hand',
  'left-leg',
  'right-leg',
  'left-foot',
  'right-foot',
  'back',
  'breast',
  'genitals-male',
  'genitals-female',
];

export const symptomTypeToLocationMapping: Record<string, string[]> = {
  'abdominal-pain-discomfort': ['abdomen', 'pelvis'],
  'anxiety-new-worsening': [],
  bleeding: regionIds3D,
  'bruising-unexplained': regionIds3D,
  chills: [],
  'confusion-disorientation': ['head'],
  constipation: ['abdomen', 'pelvis'],
  cough: ['chest', 'neck'],
  'depression-new-worsening': [],
  diarrhea: ['abdomen', 'pelvis'],
  'discharge-abnormal': ['breast', 'genitals-male', 'genitals-female'],
  dizziness: ['head'],
  'ear-pain-or-discharge': ['head'],
  'eye-pain-or-redness': ['head'],
  'fainting-syncope': ['head'],
  'fatigue-extreme': [],
  fever: [],
  headache: ['head'],
  'hearing-loss-new': ['head'],
  heartburn: ['abdomen', 'chest'],
  'irritability-agitation-unusual': [],
  'itching-persistent': regionIds3D,
  'jaw-pain': ['head'],
  'joint-pain': [
    'left-shoulder',
    'right-shoulder',
    'left-arm',
    'right-arm',
    'left-hand',
    'right-hand',
    'left-leg',
    'right-leg',
    'left-foot',
    'right-foot',
  ],
  lightheadedness: ['head'],
  'lump-mass-new': regionIds3D,
  'malaise-general-unwellness': [],
  'memory-problems-new': ['head'],
  'muscle-cramps': [
    'left-arm',
    'right-arm',
    'left-leg',
    'right-leg',
    'left-hand',
    'right-hand',
    'left-foot',
    'right-foot',
  ],
  'nasal-congestion': ['head'],
  nausea: ['abdomen'],
  numbness: regionIds3D,
  'other-symptom': regionIds3D,
  'pain-ache': regionIds3D,
  rash: regionIds3D,
  'runny-nose': ['head'],
  'shortness-of-breath': ['chest', 'neck'],
  'skin-discoloration-new': regionIds3D,
  'skin-lesion-new': regionIds3D,
  'sore-throat': ['neck', 'head'],
  'stiff-neck': ['neck'],
  'sweats-excessive': [],
  'swelling-edema': regionIds3D,
  'tingling-pins-needles': regionIds3D,
  'tinnitus-ringing-ears': ['head'],
  'urinary-issues': ['abdomen', 'pelvis', 'genitals-male', 'genitals-female'],
  'vision-blurred-double': ['head'],
  'vision-loss-partial-complete': ['head'],
  vomiting: ['abdomen'],
  'weakness-muscle': regionIds3D,
  bloating: ['abdomen'],
  'back-pain': ['back'],
};
