export const sortedSimplifiedSymptomTypes = [
  { value: 'abdominal-pain-discomfort', label: 'Abdominal Pain / Discomfort' },
  { value: 'anxiety-new-worsening', label: 'Anxiety (New or Worsening)' },
  { value: 'bleeding', label: 'Bleeding' },
  { value: 'bruising-unexplained', label: 'Bruising (Unexplained or Excessive)' },
  { value: 'chills', label: 'Chills' },
  { value: 'confusion-disorientation', label: 'Confusion or Disorientation' },
  { value: 'constipation', label: 'Constipation' },
  { value: 'cough', label: 'Cough (Persistent or Severe)' },
  { value: 'depression-new-worsening', label: 'Depression (New or Worsening)' },
  { value: 'diarrhea', label: 'Diarrhea' },
  { value: 'discharge-abnormal', label: 'Discharge (Abnormal)' },
  { value: 'dizziness', label: 'Dizziness' },
  { value: 'ear-pain-or-discharge', label: 'Ear Pain or Discharge' },
  { value: 'eye-pain-or-redness', label: 'Eye Pain or Redness' },
  { value: 'fainting-syncope', label: 'Fainting / Syncope' },
  { value: 'fatigue-extreme', label: 'Fatigue (Extreme or Prolonged)' },
  { value: 'fever', label: 'Fever' },
  { value: 'headache', label: 'Headache' },
  { value: 'hearing-loss-new', label: 'Hearing Loss (New or Sudden)' },
  { value: 'irritability-agitation-unusual', label: 'Irritability or Agitation (Unusual)' },
  { value: 'itching-persistent', label: 'Itching (Persistent or Severe)' },
  { value: 'jaw-pain', label: 'Jaw Pain' },
  { value: 'joint-pain', label: 'Joint Pain' },
  { value: 'lightheadedness', label: 'Lightheadedness' },
  { value: 'lump-mass-new', label: 'Lump or Mass (New)' },
  { value: 'malaise-general-unwellness', label: 'Malaise / General Feeling of Unwellness' },
  { value: 'memory-problems-new', label: 'Memory Problems (New or Worsening)' },
  { value: 'muscle-cramps', label: 'Muscle Cramps' },
  { value: 'nasal-congestion', label: 'Nasal Congestion' },
  { value: 'nausea', label: 'Nausea' },
  { value: 'numbness', label: 'Numbness' },
  { value: 'other-symptom', label: 'Other Symptom (Describe in Extras)' },
  { value: 'pain-ache', label: 'Pain / Ache' },
  { value: 'rash', label: 'Rash' },
  { value: 'runny-nose', label: 'Runny Nose' },
  { value: 'shortness-of-breath', label: 'Shortness of Breath / Difficulty Breathing' },
  { value: 'skin-discoloration-new', label: 'Skin Discoloration (New)' },
  { value: 'skin-lesion-new', label: 'Skin Lesion (New or Changing)' },
  { value: 'sore-throat', label: 'Sore Throat' },
  { value: 'stiff-neck', label: 'Stiff Neck' },
  { value: 'sweats-excessive', label: 'Sweats (Excessive or Night Sweats)' },
  { value: 'swelling-edema', label: 'Swelling / Edema' },
  { value: 'tingling-pins-needles', label: 'Tingling / Pins and Needles' },
  { value: 'tinnitus-ringing-ears', label: 'Tinnitus (Ringing in Ears)' },
  { value: 'urinary-issues', label: 'Urinary Issues (e.g., Pain, Frequency, Blood, Odor)' },
  { value: 'vision-blurred-double', label: 'Vision - Blurred or Double' },
  { value: 'vision-loss-partial-complete', label: 'Vision - Partial or Complete Loss' },
  { value: 'vomiting', label: 'Vomiting' },
  { value: 'weakness-muscle', label: 'Weakness (Muscle)' },
  { value: 'bloating', label: 'Bloating' },
  { value: 'heartburn', label: 'Heartburn' },
  { value: 'back-pain', label: 'Back Pain' },
].sort((a, b) => a.label.localeCompare(b.label));
export const regionIds3D = [
  'head',
  'neck',
  'chest',
  'abdomen',
  'pelvis',
  'left-shoulder',
  'right-shoulder',
  'left-arm',
  'right-arm',
  'left-hand',
  'right-hand',
  'left-leg',
  'right-leg',
  'left-foot',
  'right-foot',
  'back',
  'breast',
  'genitals-male',
  'genitals-female',
];

export const symptomTypeToLocationMapping: Record<string, string[]> = {
  'abdominal-pain-discomfort': ['abdomen', 'pelvis'],
  'anxiety-new-worsening': [],
  bleeding: regionIds3D,
  'bruising-unexplained': regionIds3D,
  chills: [],
  'confusion-disorientation': ['head'],
  constipation: ['abdomen', 'pelvis'],
  cough: ['chest', 'neck'],
  'depression-new-worsening': [],
  diarrhea: ['abdomen', 'pelvis'],
  'discharge-abnormal': ['breast', 'genitals-male', 'genitals-female'],
  dizziness: ['head'],
  'ear-pain-or-discharge': ['head'],
  'eye-pain-or-redness': ['head'],
  'fainting-syncope': ['head'],
  'fatigue-extreme': [],
  fever: [],
  headache: ['head'],
  'hearing-loss-new': ['head'],
  heartburn: ['abdomen', 'chest'],
  'irritability-agitation-unusual': [],
  'itching-persistent': regionIds3D,
  'jaw-pain': ['head'],
  'joint-pain': [
    'left-shoulder',
    'right-shoulder',
    'left-arm',
    'right-arm',
    'left-hand',
    'right-hand',
    'left-leg',
    'right-leg',
    'left-foot',
    'right-foot',
  ],
  lightheadedness: ['head'],
  'lump-mass-new': regionIds3D,
  'malaise-general-unwellness': [],
  'memory-problems-new': ['head'],
  'muscle-cramps': [
    'left-arm',
    'right-arm',
    'left-leg',
    'right-leg',
    'left-hand',
    'right-hand',
    'left-foot',
    'right-foot',
  ],
  'nasal-congestion': ['head'],
  nausea: ['abdomen'],
  numbness: regionIds3D,
  'other-symptom': regionIds3D,
  'pain-ache': regionIds3D,
  rash: regionIds3D,
  'runny-nose': ['head'],
  'shortness-of-breath': ['chest', 'neck'],
  'skin-discoloration-new': regionIds3D,
  'skin-lesion-new': regionIds3D,
  'sore-throat': ['neck', 'head'],
  'stiff-neck': ['neck'],
  'sweats-excessive': [],
  'swelling-edema': regionIds3D,
  'tingling-pins-needles': regionIds3D,
  'tinnitus-ringing-ears': ['head'],
  'urinary-issues': ['abdomen', 'pelvis', 'genitals-male', 'genitals-female'],
  'vision-blurred-double': ['head'],
  'vision-loss-partial-complete': ['head'],
  vomiting: ['abdomen'],
  'weakness-muscle': regionIds3D,
  bloating: ['abdomen'],
  'back-pain': ['back'],
};
