// This is an autogenerated file from Firebase Studio.
import { generateDiagnoses } from '@/ai/flows/generate-diagnoses';
import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    const input = await req.json();
    const result = await generateDiagnoses(input);
    return NextResponse.json(result);
  } catch (error: any) {
    console.error('API Error:', error);
    return NextResponse.json({ error: error.message || 'An error occurred.' }, { status: 500 });
  }
}
